env:
  browser: true
  es2021: true
extends:
  - 'plugin:react/recommended'
  - "plugin:@typescript-eslint/eslint-recommended"
  - "plugin:@typescript-eslint/recommended"
  - eslint:recommended
  - plugin:import/recommended
  - plugin:import/typescript
parser: '@typescript-eslint/parser'
settings:
  import/ignore: [ 'react-native' ]
  import/resolver:
    node:
      extensions: [ ".js", ".jsx", ".ts", ".tsx" ]
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
  - react-hooks
  - '@typescript-eslint'
rules:
  arrow-parens: [ 2, as-needed ]
  comma-dangle: [ 2, never ]
  react/sort-comp: 0
  react/jsx-props-no-spreading: 0
  no-use-before-define: 0
  "@typescript-eslint/no-use-before-define": 2
  import/extensions: [ 2, { js: never, ts: never, tsx: never } ]
  import/no-unresolved: [2, { ignore: [ 'react-native-device-crypto' ] }]
  no-unused-vars: 0
  "@typescript-eslint/no-unused-vars": [ 2, { argsIgnorePattern: "^_" } ]
  max-len: [ 2, 200 ]
  react/jsx-filename-extension: [ 2, { extensions: [ .js, .jsx, .ts, .tsx ] } ]
  react/require-default-props: 0
  no-console: [ 2, { allow: [ warn, error ] } ]
  no-shadow: 0
  "@typescript-eslint/no-shadow": 2
  no-underscore-dangle: 0
  import/no-extraneous-dependencies: [ 2, { devDependencies: [ "**/*.test.ts", "**/*.test.tsx" ] } ]
  '@typescript-eslint/explicit-module-boundary-types': [ 2, { allowArgumentsExplicitlyTypedAsAny: true } ]
  import/prefer-default-export: 1
  arrow-body-style: [ 2, as-needed ]
  react/jsx-closing-bracket-location: [ 2, after-props ]
  react/function-component-definition: [ 1, { namedComponents: arrow-function, unnamedComponents: arrow-function } ]
  react-hooks/exhaustive-deps: 2
  react-hooks/rules-of-hooks: 2
  one-var: 0
